# Generated by Django 5.2.16 on 2026-07-15 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='Total times this coupon can be redeemed (0 = unlimited)')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Max times a single user can use this coupon')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount required (0 = no minimum)', max_digits=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, help_text='Unique discount code (e.g. SUMMER20)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 20) or fixed amount in store currency', max_digits=10)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount to apply discount (0 = no minimum)', max_digits=10)),
                ('max_discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Maximum discount cap for percentage type (0 = no cap)', max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='Maximum number of times this discount can be used (0 = unlimited)')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('applies_to_categories', models.ManyToManyField(blank=True, related_name='discounts', to='products.category')),
                ('applies_to_products', models.ManyToManyField(blank=True, related_name='discounts', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
