# Generated by Django 5.2.16 on 2026-07-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Point of Sale', max_length=200)),
                ('project_full_name', models.CharField(default='Point of Sale Management System', max_length=300)),
                ('logo_icon', models.CharField(blank=True, default='logo/pos-icon.png', max_length=500)),
                ('logo_text', models.CharField(default='POS', max_length=50)),
                ('slogan', models.CharField(blank=True, default='Smart. Fast. Reliable.', max_length=300)),
                ('website_url', models.URLField(blank=True, default='https://example.com', max_length=500)),
                ('support_email', models.EmailField(blank=True, default='support@example.com', max_length=300)),
                ('phone_number', models.CharField(blank=True, default='+92-300-1234567', max_length=50)),
                ('store_name', models.CharField(default='My Store', max_length=300)),
                ('store_address', models.TextField(blank=True, default='123 Main Street, Lahore, Pakistan')),
                ('store_currency', models.CharField(default='PKR', max_length=10)),
                ('store_currency_symbol', models.CharField(default='Rs', max_length=10)),
                ('country_code', models.CharField(default='PK', max_length=5)),
                ('hero_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('favicon', models.CharField(blank=True, default='images/favicon.ico', max_length=500)),
                ('social_facebook', models.URLField(blank=True, default='https://facebook.com/', max_length=500)),
                ('social_instagram', models.URLField(blank=True, default='https://instagram.com/', max_length=500)),
                ('social_twitter', models.URLField(blank=True, default='https://twitter.com/', max_length=500)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.0, help_text='Global tax rate as decimal (e.g. 0.17 for 17%)', max_digits=5)),
                ('tax_label', models.CharField(default='GST', max_length=50)),
                ('receipt_footer_text', models.CharField(blank=True, default='Thank you for your purchase!', max_length=500)),
                ('receipt_width', models.PositiveIntegerField(default=80)),
                ('products_per_page', models.PositiveIntegerField(default=20)),
                ('orders_per_page', models.PositiveIntegerField(default=20)),
                ('customers_per_page', models.PositiveIntegerField(default=20)),
                ('discounts_per_page', models.PositiveIntegerField(default=20)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
