# Generated by Django 5.2.16 on 2026-07-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='logo_icon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
