# Generated by Django 5.2.16 on 2026-07-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0002_alter_storesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Browser tab icon. Recommended: 32x32 or 64x64 px, PNG/ICO format.', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='logo_icon',
            field=models.ImageField(blank=True, help_text='Store logo. Recommended: 256x256 px, PNG with transparent background.', null=True, upload_to='branding/'),
        ),
    ]
