# Generated by Django 5.2.16 on 2026-07-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0003_alter_storesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Global tax rate in % (e.g. 17 for 17%)', max_digits=5),
        ),
    ]
